"""
Auto-generated parser for Buckley Associates.
Generated by Claude API on first encounter.
"""

import re
from dataclasses import dataclass
from typing import List


@dataclass
class LineItem:
    part_no: str
    description: str
    qty: float
    unit_price: float
    unit_of_measure: str
    total: float


@dataclass
class Quote:
    vendor: str
    quote_no: str
    cust_po: str
    job_name: str
    net_total: float
    line_items: List[LineItem]


def can_parse(text: str) -> bool:
    patterns = [
        r"buckley\s+associates",
        r"buckleyonline\.com",
        r"jlavalliere@buckley",
        r"dcarter@buckley",
    ]
    return any(re.search(p, text, re.IGNORECASE) for p in patterns)


def parse(text: str) -> Quote:
    """
    Parses a Buckley Associates quote and returns a Quote object.
    """
    
    # Extract quote number
    quote_no_match = re.search(r"quote\s+number\s+(\d+)", text, re.IGNORECASE)
    quote_no = quote_no_match.group(1) if quote_no_match else ""
    
    # Extract job/project name
    job_name_match = re.search(r"project\s+([^\n]+)", text, re.IGNORECASE)
    job_name = job_name_match.group(1).strip() if job_name_match else ""
    
    # Extract location (city, state)
    location_match = re.search(r"location\s+([^\n]+)", text, re.IGNORECASE)
    location = location_match.group(1).strip() if location_match else ""
    
    # Extract total - look for the last significant price value
    total = 0.0
    
    # Find all price patterns (dollar amounts with possible commas)
    price_pattern = r"\$\s*(\d+(?:,\d{3})*(?:\.\d{2})?)"
    prices = re.findall(price_pattern, text)
    
    if prices:
        # Get the last price as the total
        last_price_str = prices[-1].replace(",", "")
        try:
            total = float(last_price_str)
        except ValueError:
            total = 0.0
    
    # Parse line items
    line_items = []
    
    # Split text into sections by product categories
    sections = re.split(r"(?:MECHANICAL PRODUCTS|SHEET METAL PRODUCTS)", text, flags=re.IGNORECASE)
    
    if len(sections) > 1:
        content = "\n".join(sections[1:])
        
        # Pattern to extract line items: Qty, Product, Description, Price
        # Look for lines starting with qty (number) followed by product info and price
        item_pattern = r"(\d+)\s+([A-Z\*\s]+?)\s+(\$[\d,\.]+)"
        
        matches = re.finditer(item_pattern, content, re.IGNORECASE)
        
        for match in matches:
            qty_str = match.group(1)
            product_desc = match.group(2).strip()
            price_str = match.group(3).replace("$", "").replace(",", "")
            
            try:
                qty = float(qty_str)
                unit_price = float(price_str)
                total_price = qty * unit_price if qty > 0 else unit_price
            except ValueError:
                continue
            
            # Extract product model/code if present
            model_match = re.search(r"MODEL\s+([A-Z0-9\-]+)", content[match.start():match.start() + 300], re.IGNORECASE)
            model = model_match.group(1) if model_match else f"ITEM-{len(line_items) + 1}"
            
            line_item = LineItem(
                part_no=model,
                description=product_desc,
                qty=qty,
                unit_price=unit_price,
                unit_of_measure="EA",
                total=total_price
            )
            line_items.append(line_item)
    
    # Fallback: if no line items found but we have a total, create a placeholder item
    if not line_items and total > 0:
        line_items.append(
            LineItem(
                part_no="SEE-QUOTE",
                description=f"Buckley Associates Quote {quote_no} - see attached PDF",
                qty=1,
                unit_price=total,
                unit_of_measure="EA",
                total=total
            )
        )
    
    quote = Quote(
        vendor="Buckley Associates",
        quote_no=quote_no,
        cust_po="",
        job_name=job_name,
        net_total=total,
        line_items=line_items
    )
    
    return quote
