"""
Auto-generated parser for Plumbers Supply Co.
Generated by Claude API on first encounter.
"""

import re
from dataclasses import dataclass, field
from typing import Optional

@dataclass
class LineItem:
    part_no: str
    description: str
    qty: float
    unit_price: float
    unit_of_measure: str
    total: float

@dataclass
class Quote:
    vendor: str
    quote_no: str
    cust_po: str
    job_name: str
    net_total: Optional[float] = None
    total: Optional[float] = None
    line_items: list[LineItem] = field(default_factory=list)

def can_parse(text: str) -> bool:
    """Check if the text is from Plumbers Supply Co."""
    return bool(re.search(r'Plumbers\s+Supply\s+Co\.?', text, re.IGNORECASE))

def parse(text: str) -> Quote:
    """Parse a Plumbers Supply Co quote."""
    
    quote = Quote(
        vendor="Plumbers Supply Co",
        quote_no="",
        cust_po="",
        job_name="",
        line_items=[]
    )
    
    # Extract quote number
    quote_no_match = re.search(r'(\d+)\s+\d+\s+Quote', text)
    if quote_no_match:
        quote.quote_no = quote_no_match.group(1)
    
    # Extract customer PO number
    cust_po_match = re.search(r'Customer PO #\s*\n\s*(\S+)', text)
    if cust_po_match:
        quote.cust_po = cust_po_match.group(1)
    
    # Extract job name / customer reference
    customer_match = re.search(r'^([A-Z0-9\s&\.]+)\s+\d+\s+\d+-\d+', text, re.MULTILINE)
    if customer_match:
        job_name = customer_match.group(1).strip()
        if job_name and job_name not in ['Quote', 'FIRST CO', 'APRILAIRE']:
            quote.job_name = job_name
    
    # Parse line items
    lines = text.split('\n')
    in_items_section = False
    for i, line in enumerate(lines):
        if 'Ord Shp BO UM Product Description' in line:
            in_items_section = True
            continue
        if in_items_section and (line.strip().startswith('---') or line.strip() == ''):
            continue
        if in_items_section and ('Total' in line or 'Taxes' in line or 'Invoice' in line or 'Last Page' in line):
            in_items_section = False
            continue
        
        if in_items_section and line.strip():
            parts = line.split()
            if len(parts) >= 5:
                try:
                    qty_ord = float(parts[0])
                    qty_shp = float(parts[1])
                    um = parts[3]
                    
                    remaining = line[line.find(um) + len(um):].strip()
                    
                    price_matches = re.findall(r'(\d+\.\d{2})', remaining)
                    if len(price_matches) >= 2:
                        unit_price = float(price_matches[-2])
                        total_price = float(price_matches[-1])
                        
                        desc_match = re.search(r'([A-Z0-9\-]+)\s+(.+?)\s+\d+\.\d{2}', remaining)
                        if desc_match:
                            part_no = desc_match.group(1).strip()
                            description = desc_match.group(2).strip()
                            
                            line_item = LineItem(
                                part_no=part_no,
                                description=description,
                                qty=qty_ord,
                                unit_price=unit_price,
                                unit_of_measure=um,
                                total=total_price
                            )
                            quote.line_items.append(line_item)
                except (ValueError, IndexError):
                    pass
    
    # Extract totals
    total_match = re.search(r'Total\s+(\d+\.\d{2})', text)
    if total_match:
        quote.net_total = float(total_match.group(1))
    
    invoice_total_match = re.search(r'Invoice Total\s+(\d+\.\d{2})', text)
    if invoice_total_match:
        quote.total = float(invoice_total_match.group(1))
    
    return quote


if __name__ == "__main__":
    sample_quote = """922 Flaherty Dr.(cid:31)
PO Box 51687
New Bedford, MA 02745(cid:31)
Phone: (508) 985-4966 Fax: 508-985-4992
www.plumberssupplyco.com
8481 19116809-00 Quote
DENOMMEE PLUMBING & HEATING CAPCO Energy Supply
21 WESTECH DRIVE 3 Rath Road
TYNGSBORO, MA 01879 Woburn, MA 01801
(781)721-0303
Order Date Ship Via Whse Ship Instruction
06/01/26 13:35 Deliver OT WB
Customer PO # Req.Ship Reference Taken By
NANTUCKET 06/01/26 mxb
Qty Qty Qty
Ord Shp BO UM Product Description List Unit Amount
-----------------------------------------------------------------------------------------------------------------------------------
1 0 E 39832 FIRST CO 8VMB-3HW VAR SPD A/H 4-PIPE 3407.69 3241.46 3241.46
07/26/E07/6
1 0 E 99478 APRILAIRE E100W W/WIFI DEHUMIDIFIER UNIT 100PIN 3511.05 1733.05 1733.05
07/26/E07/6
Total 4974.51
Taxes 310.91
Invoice Total 5285.42
Last Page Page 1"""
    
    print("Can parse:", can_parse(sample_quote))
    result = parse(sample_quote)
    print(f"Vendor: {result.vendor}")
    print(f"Quote No: {result.quote_no}")
    print(f"Customer PO: {result.cust_po}")
    print(f"Job Name: {result.job_name}")
    print(f"Net Total: {result.net_total}")
    print(f"Invoice Total: {result.total}")
    print(f"Line Items ({len(result.line_items)}):")
    for item in result.line_items:
        print(f"  - {item.part_no}: {item.description} - Qty: {item.qty} {item.unit_of_measure} @ ${item.unit_price} = ${item.total}")
