"""
Auto-generated parser for Plumbers Supply Co.
Generated by Claude API on first encounter.
Fixed: multi-signal can_parse() so PDF domain text (plumberssupplyco.com)
matches even when vendor name spacing is lost in PDF extraction.
"""
import re
from dataclasses import dataclass, field
from typing import List


@dataclass
class LineItem:
    part_no: str = ""
    description: str = ""
    qty: float = 1.0
    unit_price: float = 0.0
    unit_of_measure: str = "EA"
    total: float = 0.0


@dataclass
class ParsedQuote:
    vendor: str = "Plumbers Supply Co."
    quote_no: str = ""
    cust_po: str = ""
    job_name: str = ""
    total: float = 0.0
    line_items: List[LineItem] = field(default_factory=list)


def can_parse(text: str) -> bool:
    patterns = [
        r"plumbers'?\s*supply",       # "Plumbers Supply" or "Plumbers' Supply"
        r"plumberssupply",            # domain: plumberssupply.com
        r"plumberssupplyco",          # domain: plumberssupplyco.com
        r"508[\s.\-]?985[\s.\-]?4966",# phone
        r"922\s+Flaherty",            # street address
        r"New Bedford,?\s*MA",        # city/state
        r"PO\s+Box\s+51687",          # PO box
    ]
    return any(re.search(p, text, re.IGNORECASE) for p in patterns)


def parse(text: str) -> ParsedQuote:
    quote = ParsedQuote()

    # Vendor name
    quote.vendor = "Plumbers Supply Co."

    # Quote number
    m = re.search(r'(?:quote|bid|order|#)\s*[:#]?\s*([A-Z0-9\-]+)', text, re.IGNORECASE)
    if m:
        quote.quote_no = m.group(1).strip()

    # Customer PO
    m = re.search(r'(?:cust(?:omer)?\.?\s*po|purchase\s*order)[:\s#]*([A-Z0-9\-]+)', text, re.IGNORECASE)
    if m:
        quote.cust_po = m.group(1).strip()

    # Job name
    m = re.search(r'(?:job|project|ship\s*to)[:\s]+([^\n]{3,50})', text, re.IGNORECASE)
    if m:
        quote.job_name = m.group(1).strip()

    # Total
    totals = re.findall(r'(?:total|amount)[^\d]*\$?([\d,]+\.\d{2})', text, re.IGNORECASE)
    if totals:
        try:
            quote.total = float(totals[-1].replace(',', ''))
        except ValueError:
            pass

    # Line items: look for rows with qty, part number, description, price
    line_pattern = re.compile(
        r'(\d+)\s+'                          # qty
        r'([A-Z0-9\-\.\/]+)\s+'              # part no
        r'(.+?)\s+'                          # description
        r'(\d[\d,]*\.\d{2})\s+'             # unit price
        r'(\d[\d,]*\.\d{2})',                # ext price
        re.IGNORECASE
    )
    for m in line_pattern.finditer(text):
        try:
            qty        = float(m.group(1))
            part_no    = m.group(2).strip()
            desc       = m.group(3).strip()
            unit_price = float(m.group(4).replace(',', ''))
            ext_price  = float(m.group(5).replace(',', ''))
            quote.line_items.append(LineItem(
                part_no=part_no,
                description=desc,
                qty=qty,
                unit_price=unit_price,
                unit_of_measure="EA",
                total=ext_price,
            ))
        except (ValueError, IndexError):
            continue

    # Fallback: if no line items parsed but we have a total
    if not quote.line_items and quote.total > 0:
        quote.line_items.append(LineItem(
            part_no="SEE-QUOTE",
            description=f"Plumbers Supply Co. Quote {quote.quote_no} - see attached PDF",
            qty=1,
            unit_price=quote.total,
            unit_of_measure="EA",
            total=quote.total,
        ))

    return quote
