"""
Auto-generated parser for Trane U.S. Inc..
Generated by Claude API on first encounter.
"""

import re
from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class LineItem:
    part_no: str
    description: str
    qty: float
    unit_price: float
    unit_of_measure: str
    total: float


@dataclass
class Quote:
    vendor: str
    quote_no: str
    cust_po: str
    job_name: str
    net_total: float
    line_items: List[LineItem] = field(default_factory=list)


def can_parse(text: str) -> bool:
    return bool(re.search(
        r'Trane\s+U\.S\.?\s+Inc\.?|Trane\s+Technologies|trane\.com',
        text, re.IGNORECASE
    ))


def parse(text: str) -> Optional[Quote]:
    """
    Parse a Trane U.S. Inc. quote and extract key information.
    Returns Quote object or None if parsing fails.
    """
    if not can_parse(text):
        return None
    
    quote = Quote(
        vendor="Trane U.S. Inc.",
        quote_no="",
        cust_po="",
        job_name="",
        net_total=0.0,
        line_items=[]
    )
    
    # Extract Proposal/Quote Number
    proposal_match = re.search(r'Proposal\s+Number:\s*([A-Z0-9\-]+)', text, re.IGNORECASE)
    if proposal_match:
        quote.quote_no = proposal_match.group(1).strip()
    
    # Extract Customer PO (if present)
    po_match = re.search(r'(?:Customer\s+)?PO\s*[#:]?\s*([A-Z0-9\-]+)', text, re.IGNORECASE)
    if po_match:
        quote.cust_po = po_match.group(1).strip()
    
    # Extract Job Name
    job_match = re.search(r'Job\s+Name:\s*([^\n]+?)(?:\s+Proposal|$)', text, re.IGNORECASE)
    if job_match:
        quote.job_name = job_match.group(1).strip()
    
    # Extract Net Total Price
    total_match = re.search(
        r'Total\s+Net\s+Price\s+(?:SPLITS|RENEWAIRE)?\s*(?:\(.*?\))?\s*\.+\s*\$\s*([\d,]+\.?\d*)',
        text,
        re.IGNORECASE | re.DOTALL
    )
    if total_match:
        total_str = total_match.group(1).replace(',', '')
        quote.net_total = float(total_str)
    
    # Try to extract line items from Tag Data tables
    line_items = _extract_line_items(text)
    quote.line_items = line_items
    
    # REQUIRED FALLBACK: if no line items but we have a total, create one synthetic item
    if not quote.line_items and quote.net_total > 0:
        quote.line_items.append(
            LineItem(
                part_no="SEE-QUOTE",
                description=f"Trane U.S. Inc. Quote {quote.quote_no} - see attached PDF",
                qty=1.0,
                unit_price=quote.net_total,
                unit_of_measure="EA",
                total=quote.net_total
            )
        )
    
    return quote


def _extract_line_items(text: str) -> List[LineItem]:
    """
    Extract line items from Tag Data sections and Product Data.
    Handles both VRF and Renewaire ERV formats.
    """
    items = []
    
    # Pattern 1: Extract from Tag Data - VRF section
    # Looking for lines with: Qty Model Description Tag
    tag_data_vrf = re.search(
        r'Tag\s+Data\s*-\s*VRF\s*\n(.*?)(?:\n\s*Notes:|$)',
        text,
        re.IGNORECASE | re.DOTALL
    )
    
    if tag_data_vrf:
        vrf_block = tag_data_vrf.group(1)
        # Match lines with qty, model, description, tag pattern
        # Format: Qty Model Description Tag
        lines = vrf_block.split('\n')
        for line in lines:
            line = line.strip()
            if not line or line.startswith('Qty') or line.startswith('Tag'):
                continue
            
            # Try to parse qty, model, description
            parts = re.split(r'\s{2,}', line)
            if len(parts) >= 3:
                try:
                    qty_str = parts[0].strip()
                    model = parts[1].strip()
                    desc = parts[2].strip()
                    
                    # Extract qty as number
                    qty_match = re.match(r'^(\d+)', qty_str)
                    if qty_match:
                        qty = float(qty_match.group(1))
                        items.append(
                            LineItem(
                                part_no=model,
                                description=desc,
                                qty=qty,
                                unit_price=0.0,
                                unit_of_measure="EA",
                                total=0.0
                            )
                        )
                except (ValueError, IndexError):
                    continue
    
    # Pattern 2: Extract from Renewaire ERV ALT section
    renewaire_match = re.search(
        r'Tag\s+Data\s*-\s*Renewaire\s+ERV\s+ALT.*?\n(.*?)(?:\nProduct\s+Data|$)',
        text,
        re.IGNORECASE | re.DOTALL
    )
    
    if renewaire_match:
        renewaire_block = renewaire_match.group(1)
        lines = renewaire_block.split('\n')
        for line in lines:
            line = line.strip()
            if not line or line.startswith('Item') or line.startswith('Tag'):
                continue
            
            parts = re.split(r'\s{2,}', line)
            if len(parts) >= 3:
                try:
                    item_tag = parts[0].strip()
                    qty_str = parts[1].strip()
                    model = parts[2].strip()
                    
                    qty_match = re.match(r'^(\d+)', qty_str)
                    if qty_match:
                        qty = float(qty_match.group(1))
                        items.append(
                            LineItem(
                                part_no=model,
                                description=f"{model} - {item_tag}",
                                qty=qty,
                                unit_price=0.0,
                                unit_of_measure="EA",
                                total=0.0
                            )
                        )
                except (ValueError, IndexError):
                    continue
    
    # Pattern 3: Look for additional components in accessory lines
    accessory_pattern = r'^([A-Z0-9\-]+)\s+-?\s+(.+)$'
    accessory_lines = [
        'TC7D-E DIGITAL TIMER ENCLOSURE',
        '07HEDF - FLANGE KIT RECT 12" X 12"'
    ]
    
    for line in text.split('\n'):
        line = line.strip()
        for acc_line in accessory_lines:
            if acc_line.lower() in line.lower():
                parts = re.split(r'\s+-\s+', line, 1)
                if len(parts) == 2:
                    items.append(
                        LineItem(
                            part_no=parts[0].strip(),
                            description=parts[1].strip(),
                            qty=1.0,
                            unit_price=0.0,
                            unit_of_measure="EA",
                            total=0.0
                        )
                    )
    
    return items
